### ISSUE TITLE
json frontmatter in md files

### ISSUE THREAD

**Issue by maks** [mantoni/blogdown#1]
What an awesome tool, thanks for writing this, I've given up on continuing my enhancements to susi as this is so much closer to what I want and more powerful in many way (lists functionality is *very* nice).
One thing I miss though is being able to put json in as front matter of the md files instead of in separate json files alongside - would this be something you'd consider?

**Comment by maks** [comment]
Sorry my mistake, just spotted that d2535322ce9e74eac4ce48aa474b627321f96b1f actually implements exactly this. So its only that its not documented in the readme.

**Comment by mantoni** [comment]
Thanks @maks! I wrote this tool for a purpose that it fulfilled. I might come back to it, but currently, I have no capacity to look after it. If you're interested, you're welcome to maintain it.

**Comment by maks** [comment]
Thanks, I've started finding a couple of things I needed to add to support to work with generating my website at the moment, so I'm committing them to master on my [fork](https://github.com/maks/blogdown) in case anyone else wants these extra features.

**Comment by mantoni** [comment]
How about contributing these changes back to the repo here?
