### ISSUE TITLE
new release for npm

### ISSUE THREAD

**Issue by maks** [mantoni/blogdown#12]
@mantoni  Would it please be possible to tag master and do a new release to npm, as currently I'm still using my own local fork as npm does not have the last set of changes in master.

**Comment by mantoni** [comment]
Sure, I can do that tonight, or you can do it yourself :shipit:

**Comment by mantoni** [comment]
Try making a major release: `npm version major`

**Comment by maks** [comment]
Thanks! I didn't realise I could do it myself, I'll do it today.

**Comment by maks** [comment]
I haven't done a release to npm for quite a while, what a very nice publishing experience! And I really like how your studio changes tool makes the changelog such an easy automated step, will definintely be using it on other projects from now on too,

**Comment by mantoni** [comment]
You're welcome 😊
