### ISSUE TITLE
Linter not working and project in an outdated state

### ISSUE THREAD

**Issue by mantoni** [mantoni/blogdown#5]
I thought I'd set up travis to get a better experience in pull requests and discovered that the linter does not work any more. All in all the project is in a very old state and needs a refresh regarding tooling being used. The things I'd change are:

- Use eslint
- Migrate tests over to Mocha
- Remove Makefile and use npm scripts instead
- Use [Studio Changes](https://github.com/javascript-studio/studio-changes) as the release tool

@maks What are your thoughts? Any of the above that you wouldn't like?

**Comment by maks** [comment]
This is great, having eslint is good!
And I'd not come across studio changes before, looks like a great tool!
I'm happy with all of the above. :+1:

**Comment by mantoni** [comment]
Ok, all done. Closing. I feel like I should cut a `v1.0.0` release ✨ 😄
